# Generated by Django 4.1.13 on 2024-08-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_clothitems_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothitems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='AdminApp.category'),
        ),
        migrations.AlterField(
            model_name='itemimages',
            name='cloth_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AdminApp.clothitems'),
        ),
    ]
