# Generated by Django 4.1.13 on 2024-08-10 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_clothspecification_cloth_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('sizes', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='clothspecification',
            old_name='size_id',
            new_name='item_spec_id',
        ),
        migrations.RemoveField(
            model_name='clothspecification',
            name='item_size',
        ),
        migrations.AddField(
            model_name='clothspecification',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.size'),
        ),
    ]
