# Generated by Django 4.1.13 on 2024-08-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_size_rename_size_id_clothspecification_item_spec_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothitems',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
