# Generated by Django 4.1.13 on 2024-08-12 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_clothitems_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothspecification',
            name='cloth_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothspec', to='AdminApp.clothitems'),
        ),
    ]
