# Generated by Django 4.1.13 on 2024-08-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_alter_clothspecification_cloth_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistrict', to='AdminApp.state'),
        ),
    ]
