# Generated by Django 4.1.13 on 2024-08-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
