# Generated by Django 4.1.13 on 2024-08-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
