# Generated by Django 4.1.13 on 2024-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_cart_total_price_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
