# Generated by Django 4.1.13 on 2024-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_remove_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ph_no',
            field=models.IntegerField(null=True),
        ),
    ]
