# Generated by Django 4.1.13 on 2024-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_user_ph_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ph_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
