# Generated by Django 4.1.13 on 2024-08-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_alter_clothspecification_cloth_item'),
        ('UserApp', '0014_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.size'),
        ),
    ]
