# Generated by Django 4.1.13 on 2024-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
