# Generated by Django 4.1.13 on 2024-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0022_otp_remove_user_otp_remove_user_otp_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
