# Generated by Django 4.1.13 on 2024-08-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0024_alter_orderitems_cloth_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
