# Generated by Django 5.1 on 2024-08-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0026_paymentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='razorpay_payment_signature',
        ),
    ]
